### ISSUE TITLE
Include acknowledgment tables in submission

### ISSUE THREAD

**Issue by evogytis** [evogytis/fluB#20]
The second line of the Methods section states "accession numbers and laboratory acknowledgements can be found in the supplementary information." Please specify from which supplementary table or figure can we find that information.

**Comment by evogytis** [comment]
I forgot to include the acknowledgment table during the initial submission to eLife. Maybe it's worth putting all the data we have on Dryad?

**Comment by rambaut** [comment]
Does any of it come from GISAID? 

Andrew

**Comment by evogytis** [comment]
Not directly, no. I'm thinking subsampled trees, mcc trees, XMLs with sequences redacted out, GISAID acknowledgment table, LD data and the files used to make the figures.

**Comment by trvrb** [comment]
Reproducible research is a good thing.  You've already done a great job with this.  Perhaps just starting with a link to the GitHub repo?  On acceptance put things on Dryad?
