### ISSUE TITLE
Alternative methods.

### ISSUE THREAD

**Issue by evogytis** [evogytis/fluB#22]
> The paper uses a straightforward method for the bioinformatic inference of reassortment, but without much of a statistical evaluation or comparison with other methods. A number of comparable methods have been published in recent years (e.g. Rabadan R, Levine A J, Krasnitz M. Non-random reassortment in human inﬂuenza A viruses. Inﬂuenza and Other Respiratory Viruses 2 (2008), Westgeest K B et al. Genomewide Analysis of Reassortment and Evolution of Human Influenza A(H3N2) Viruses Circulating between 1968 and 2011. Journal of Virology (2014)). Benchmarking the results against these methods would be useful; this applies, in particular, to the statistically subtle problem of identifying reassortment rates within one lineage.

**Comment by evogytis** [comment]
I don't have much faith in blob plots like the one in Rabadan et al (mostly for precision reasons) and I'm not going to run our data with MrBayes in order to use GiRaF. Tanglegrams are pointless, because we can infer inter-lineage reassortments and visualize them in a more interpretable way (Figure 6) than an 8x7 grid of tanglegrams could.

**Comment by trvrb** [comment]
I completely agree with you here.

**Comment by hxnx-sam** [comment]
I don't think you need MrBayes trees to run Giraf, I think you can use a premade tree set ( but I've not looked at Giraf in a while) but you might need to strip out the extra node and branch annotations in the beast trees. Mojca ran Giraf I think, and we are both coming tomorrow (Friday).
