### ISSUE TITLE
Remove compiled PDF from repo

### ISSUE THREAD

**Issue by trvrb** [evogytis/fluB#3]
I've gone back and forth about this in my own papers, but I think it's probably best to remove fluB.pdf from the repo.  Git is really bad at tracking binary files.  Each small change to the .tex source results in a large change to the PDF.  This will cause repo bloat.  It will also make merging difficult if that is ever desired.

Unfortunately, this makes it harder for other to immediately see your work.  Thinking now, you could have a separate branch "publish" for compiled PDFs or HTML or Markdown or whatever.  Development goes on in master branch and compiled versions are committed to "publish".  Not at all necessary to have however.

**Comment by evogytis** [comment]
Hopefully fixed now. I'll look into converting LaTeX into HTML.
