### ISSUE TITLE
The discussion is long and somewhat disorganized.

### ISSUE THREAD

**Issue by evogytis** [evogytis/fluB#36]
The discussion is long and somewhat disorganized.  I think the authors should 
spend some time improving the writing here, and shortening it.  The central 
theme of the paper is this PB1-PB2-HA complex, and I would structure the 
discussion to address the main questions surrounding this complex.  
Something like:
1.  Why are these segments so tightly linked at the genetic level?

1a.  Co-adaptation?  Possibly.  There is good functional evidence that
PB1 and PB2 should be co-adapted.  There is some evidence, but much less,
that HA should be co-adapted to PB1-PB2

1b.  Simple divergence?  Possibly, especially if epistatic interactions
cause an adapted PB1-PB2-HA complex to synergistically interact with the genotype
defined by the other five segments.  But, we do see reassortment among the other
five segments, so the evidence here is mixed.
1.  Is frequency-dependent selection allowing Flu B to maintain two HA types (in
   the same way that Flu A maintains two circulating subtypes in the population)?
2.  Are Flu B population sizes big or small?  Could stochastic events have played
   a role in Flu B's population structure?  Does the lack of sequence data in the 1980s
   and early 1990s affect our conclusions?
3.  Will influenza B speciate?

**Comment by evogytis** [comment]
Seems like a decent structure for the discussion. Will try to organize the manuscript accordingly.

**Comment by trvrb** [comment]
I agree about trimming down the discussion.  However, I'm still not sure if 1a and 1b are meaningfully different.  If I understand things correctly, both assume that there is an epistatic link between PB1-PB2(-HA), but that 1a assumes it got there by selection and 1b assumes it got there by [DM](http://en.wikipedia.org/wiki/Bateson-Dobzhansky-Muller_Model) drift.  I would tend to lump 1a and 1b together and note that we really can't know whether it was selection or drift that brought about epistasis.  I personally don't think that "co-adapted gene complex" means positive selection, but there may have been some confusion here.  My suggested structure:
1. Why are these segments so tightly linked at the genetic level?
   
   a. Process.  Co-adaptation? Simple divergence?
   
   b. Functional mechanism.
2. What allowed this to happen in B?
   
   a. Is frequency-dependent selection allowing Flu B to maintain two HA types (in
   the same way that Flu A maintains two circulating subtypes in the population)?
   
   b. Are Flu B population sizes big or small? Could stochastic events have played
   a role in Flu B's population structure? Does the lack of sequence data in the 1980s
   and early 1990s affect our conclusions?
3. Will influenza B speciate?

**Comment by evogytis** [comment]
Fixed by 3b69396818ddeff5f1d4ffb1425c2768eab20162.
