### ISSUE TITLE
Selection wording.

### ISSUE THREAD

**Issue by evogytis** [evogytis/fluB#37]
Throughout the discussion "balancing selection" is used in a way I don't
understand. On page 15, if Vic and Yam are antigenically dissimilar, then it is 
frequency-dependent selection -- not balancing selection -- that prevents one 
genotype from driving the other to extinction.

**Comment by evogytis** [comment]
Will change the wording. Too minor a point to argue.

**Comment by trvrb** [comment]
Thanks for the making the change.  I really think that balancing selection is the more generic term.  For example:

https://www.sciencemag.org/content/339/6127/1578.abstract

However, I agree it's not worth arguing.
