### ISSUE TITLE
Make sure all supp figures are referenced

### ISSUE THREAD

**Issue by trvrb** [evogytis/fluB#39]
Figure S14 (`deltaTMRCAtrees`) is not referenced from either the main text or the supplement.  Ideally, all supp figures will be referenced from the main text and their numbering reflect their chronological use in the main text.

**Comment by evogytis** [comment]
I'll reference that one to justify the normalization procedure (that's why it's there to begin with).

**Comment by evogytis** [comment]
Closed via 56986b125056e560c8883553f2bd0c4ef5aec959
