### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by trvrb** [evogytis/fluB#7]
Be careful with the use of the term "lineages".  At some points in the manuscript it means every branch in the tree (a common phylogenetic use) and at other points it means Vic and Yam only.  I'd suggest keeping "lineages" to just Vic and Yam and using words like "viruses" or "branches" for other cases.

**Comment by evogytis** [comment]
Changed `InfB_tmrcaOT_lines.png` to refer to TMRCAs between branches via 82686f082d79f0d18e970bcb48f685748af4cca6, text was changed too. Can't find any mentions of 'lineage' in the manuscript that refer to anything but Vic and Yam. Closing issue until more can be discovered.
